/*
 * File: app/view/case/CaseListingViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SolarUI.view.case.CaseListingViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.casesCtrl',

    showView: function(view) {
        var references = this.getReferences();

        var display = references.cardDisplayPanel;
        var layout = display.getLayout();

        var viewRef = this.lookupReference(view);

        layout.setActiveItem(viewRef);

    },

    onGridpanelSelect: function(rowmodel, record, index, eOpts) {
        // grab a reference to the detailPanel
        // http://www.sencha.com/blog/using-viewcontrollers-in-ext-js-5

        var detailPanel = this.lookupReference('detailPnlRef');

        // update the detailPanel with data - this will trigger the tpl to become updates
        detailPanel.update(record.data);

        // Show form
        this.showView('detailPnlRef');

    },

    add: function(button, e, eOpts) {
        var references = this.getReferences(),
            formPanel = this.getReferences().caseFormRef,
            form = formPanel.getForm();

        //create a new model using alias
        var newRecord = Ext.create('model.case');

        // Clear form
        form.reset();

        // Set record
        form.loadRecord(newRecord);

        // Set title
        formPanel.setTitle('Add Case');

        // Show form
        this.showView('caseFormRef');
    }

});
