/*
 * File: app/view/case/CaseListingViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SolarUI.view.case.CaseListingViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.cases',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        casemodel: {
            model: 'SolarUI.model.CaseModel',
            data: [
                {
                    case: 'VG05',
                    group: 'A',
                    sub_group: '2',
                    library: '11',
                    company: 'The Hartford Benefit Protection Master Trust',
                    certs: 32000,
                    case_admin: 'cmanneta'
                },
                {
                    case: 'VG07',
                    group: 'B',
                    sub_group: '1',
                    library: '10',
                    company: 'The Bankers Greedy Master Trust',
                    certs: 10000,
                    case_admin: 'dmerril'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});