/*
 * File: app/view/case/CaseListing.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SolarUI.view.case.CaseListing', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.caselisting',

    requires: [
        'SolarUI.view.case.CaseListingViewModel',
        'SolarUI.view.case.CaseListingViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.XTemplate',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Separator'
    ],

    controller: 'casesCtrl',
    viewModel: {
        type: 'cases'
    },
    frame: true,
    height: 250,
    width: '100%',
    title: 'Cases',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    bind: {
        controller: 'casesCtrl'
    },
    items: [
        {
            xtype: 'gridpanel',
            flex: 1,
            reference: 'caseGridRef',
            bind: {
                store: '{casemodel}'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'case',
                    text: 'Case'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'company',
                    text: 'Company',
                    flex: 1
                }
            ],
            listeners: {
                select: 'onGridpanelSelect'
            }
        },
        {
            xtype: 'panel',
            flex: 1,
            reference: 'cardDisplayPanel',
            layout: 'card',
            title: 'Detail',
            items: [
                {
                    xtype: 'panel',
                    reference: 'detailPnlRef',
                    tpl: [
                        '<p><b>Number of Lives:</b>{certs}</p>',
                        '<p><b>Case Admin:</b>{case_admin}</p>'
                    ]
                },
                {
                    xtype: 'form',
                    reference: 'caseFormRef',
                    bodyPadding: 10,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Case',
                            name: 'case'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Company',
                            name: 'company'
                        },
                        {
                            xtype: 'button',
                            text: 'Save'
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            flex: 1,
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    text: 'Add',
                    listeners: {
                        click: 'add'
                    }
                },
                {
                    xtype: 'tbseparator',
                    width: 100
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Filter'
                }
            ]
        }
    ]

});